
before_install:
  - sudo add-apt-repository -y ppa:coolwanglu/pdf2htmlex
  - sudo apt-get -qq update
  - sudo apt-get install  tesseract-ocr
  - sudo apt-get install -y pdf2htmlex
  - sudo apt-get install tesseract-ocr 
  - sudo apt-get install tesseract-ocr-pol
language: java
