dist: xenial
before_install:
  - sudo apt-get -qq update
  - git clone https://github.com/aleksey-nikolaev/poppler.git
  - cd poppler
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ..
  - sudo apt-get install tesseract-ocr 
  - sudo apt-get install tesseract-ocr-pol
  - git clone git://github.com/coolwanglu/pdf2htmlEX.git
  - cd pdf2htmlEX
  - cmake .
  - make
  - sudo make install
language: java
